package cn.lp.statemachine.enums;


public enum EventsEnum {
    UPDATE_CHANNEL_ORDER_EVENT,
    UPDATE_CHANNEL_ORDER_BY_CHANNEL_NOTIFY_EVENT,
    UPDATE_LOAN_ORDER_EVENT,
    UPDATE_LOAN_ORDER_REPAYMENT_STATUS_EVENT,
    UPDATE_LOAN_CAR_APPLY_EVENT,
    UPDATE_CALL_ACCOUNT,
    NOTIFY_EVENT
}
